export const defaultData = {
    chave: 1,
    nome: "João Silva",
    telefone: "(11) 98765-4321",
    foto: "https://static.vecteezy.com/system/resources/thumbnails/047/268/484/small/cheerful-software-developer-focused-on-his-computer-at-workstation-free-photo.jpeg",
    resumo: "Desenvolvedor Fullstack com experiência em React, Node.js e bancos de dados relacionais e não relacionais. Apaixonado por criar soluções escaláveis e eficientes.",
    campos: [
      { nome_campo: "Email", tipo_campo: "TEXTO", valor_campo: "joao.silva@example.com" },
      { nome_campo: "LinkedIn", tipo_campo: "TEXTO", valor_campo: "linkedin.com/in/joaosilva" },
      { nome_campo: "GitHub", tipo_campo: "TEXTO", valor_campo: "github.com/joaosilva" },
    ],
    experiencias: [
      {
        chave: "exp-1",
        nome_experiencia: "Desenvolvedor Sênior",
        tipo_experiencia: "EXPERIENCIA",
        descricao_experiencia: "Desenvolvimento e manutenção de aplicações web utilizando React e Node.js.",
        periodo_inicio: "2020-01-01",
        periodo_fim: "",
        em_curso: true,
        hashtags: "react nodejs javascript typescript",
        nome_instituicao: "Tech Solutions Ltda.",
        chave_instituicao: "tech-solutions-1",
      },
      {
        chave: "exp-2",
        nome_experiencia: "Desenvolvedor Pleno",
        tipo_experiencia: "EXPERIENCIA",
        descricao_experiencia: "Participação no desenvolvimento de novas funcionalidades e correção de bugs.",
        periodo_inicio: "2018-03-01",
        periodo_fim: "2019-12-31",
        em_curso: false,
        hashtags: "angular java springboot",
        nome_instituicao: "Web Innovators S.A.",
        chave_instituicao: "web-innovators-1",
      },
      {
        chave: "cert-1",
        nome_experiencia: "Certificado AWS Cloud Practitioner",
        tipo_experiencia: "CERTIFICADO",
        descricao_experiencia: "Certificação fundamental em conceitos de nuvem AWS.",
        periodo_inicio: "2023-05-01",
        periodo_fim: "",
        em_curso: false,
        hashtags: "aws cloud certificacao",
        nome_instituicao: "Amazon Web Services",
        chave_instituicao: "aws-cert-1",
      },
      {
        chave: "cert-1",
        nome_experiencia: "Certificado AWS Cloud Practitioner",
        tipo_experiencia: "ADICIONEI",
        descricao_experiencia: "Certificação fundamental em conceitos de nuvem AWS.",
        periodo_inicio: "2023-05-01",
        periodo_fim: "",
        em_curso: false,
        hashtags: "aws cloud certificacao",
        nome_instituicao: "Amazon Web Services",
        chave_instituicao: "aws-cert-1",
      },
    ],
}